syntax enable
set background=dark
set noerrorbells
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set smartindent
set linebreak
set nu
set rnu
set so=8
set showmatch
set showbreak=+++
set noswapfile
set incsearch
set termguicolors
set signcolumn = "yes"
set colorcolumn = "100"
set splitright
set splitbelow

nnoremap <SPACE> <Nop>
let mapleader = " "

noremap <Up> <Nop>
noremap <Down> <Nop>
noremap <Left> <Nop>
noremap <Right> <Nop>

nmap <leader>y "+y
nmap <leader>p "+p
nmap <leader>P "+P

set clipboard+=unnamedplus
