#!/usr/bin/env sh

# author: Bruno Parolini brunoparolini@gmail.com
# description: Defines env variables

# A link must be created using the following command:
# ln -s $HOME/.dotfiles/apps/.profile $HOME/.profile

. "$HOME/.dotfiles/apps/xdg_defaults.sh"

export EDITOR="/usr/bin/nvim"

export GH_IDE_TOKEN="***REMOVED***"

export JAVA_HOME="$HOME/apps/java"
# export _JAVA_OPTIONS="-Dawt.useSystemAAFontSettings=lcd -Dswing.aatext=true -Dsun.java2d.xrender=true"
export JDTLS_HOME="$HOME/.jdtls/org.eclipse.jdt.ls.product/target/repository"

export DOTNET_ROOT="$HOME/apps/dotnet"

export PIPENV_VENV_IN_PROJECT=1

export GRADLE_USER_HOME="$HOME/.gradle"

export NVM_SYMLINK_CURRENT=true
export NVM_NODE_PATH="$HOME/.nvm/current"

export GOROOT="$HOME/apps/go"
export GOPATH="$HOME/projetos/go"

export RUSTUP_HOME="$HOME/apps/rust"
export CARGO_HOME="$HOME/apps/cargo"

export KAFKA_HOME="$HOME/apps/kafka"

export KUBE_EDITOR="nvim"

if [[ "$ID" = "fedora" ]]
then
    export DOCKER_HOST="unix:$XDG_RUNTIME_DIR/podman/podman.sock"
else
    systemctl --user enable docker.service
    systemctl --user start docker.service
    export DOCKER_HOST="unix://$XDG_RUNTIME_DIR/docker.sock"
fi

. "$HOME/.dotfiles/apps/plasma_env.sh"
