syntax enable
set background=dark
set noerrorbells
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set smartindent
set linebreak
set nu
set rnu
set showmatch
set showbreak=+++
set noswapfile
set incsearch
set termguicolors
set signcolumn = "yes"
set colorcolumn = "100"

noremap <Up> <Nop>
noremap <Down> <Nop>
noremap <Left> <Nop>
noremap <Right> <Nop>

set clipboard+=unnamedplus
