# Set the .dotfile path env variables
export DOTFILES="$HOME/.dotfiles"

# Sets all the default values for the XDK environment variables
. "$DOTFILES/zsh/xdg_defaults"

# Sets ZSH config directory
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"

# Sets the default history file
export HISTFILE="$ZDOTDIR/.zhistory"
export HISTSIZE=10000
export SAVEHIST=10000

# Sets the default TERM
export TERM="xterm-256color"

# Sets the default editor
export EDITOR="nvim"
export VISUAL="nvim"

# Sets development environment variables
source "$DOTFILES/zsh/dev_env"

# Sets fzf environment variables
if [ $commands[rg] ]; then
    export FZF_DEFAULT_COMMAND="rg --files --hidden --glob '!.git' --glob '!.cache' --glob '!.venv' --glob '!venv' 2> /dev/null"
    export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
fi
export FZF_DEFAULT_OPTS="--multi --height=50% --margin=5%,2%,2%,5% --layout=reverse-list --border=double --border-label='Fuzzy Finder' --info=inline --header='CTRL-C or ESC to quit'"
export FZF_COMPLETION_DIR_COMMANDS="cd pushd rmdir tree"
