# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
    source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="powerlevel10k/powerlevel10k"

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
    git
    dotenv
    pipenv
    sdk
    zsh-syntax-highlighting
    zsh-autosuggestions
)

fpath+=$HOME/.zfunc
fpath=($ZDOTDIR/external $fpath)
fpath+=${ZSH_CUSTOM:-${ZSH:-~/.oh-my-zsh}/custom}/plugins/zsh-completions/src

source $ZSH/oh-my-zsh.sh

# User configuration

# You may need to manually set your language environment
export LANG="pt_BR.UTF-8"
export LC_ALL="pt_BR.UTF-8"

# Directory stack config
setopt AUTO_PUSHD
setopt PUSHD_IGNORE_DUPS
setopt PUSHD_SILENT

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
source "$ZDOTDIR/aliases"

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"

source /etc/os-release

if [[ "$ID" != "fedora" ]]
then
    source "$DOTFILES/olxbr/scripts/tokens"
    source "$DOTFILES/olxbr/scripts/kubernetes_aliases"
    # source "$DOTFILES/olxbr/scripts/aws_envs"
fi

if [ $commands[sdk] ]
then
    source <(sdk env zsh)
fi

if [ $commands[npm] ]
then
    source <(npm completion)
fi

if [ $commands[pipenv] ]
then
    eval "$(_PIPENV_COMPLETE=zsh_source pipenv)"
fi

if [ $commands[kubectl] ]
then
    source <(kubectl completion zsh)
fi

if [ $commands[minikube] ]
then
    source <(minikube completion zsh)
fi

if [ $commands[direnv] ]
then
    source <(direnv hook zsh)
fi

if [ $commands[rustup] ]
then
    if [ ! -f "$HOME/.zfunc/_rustup" ]; then
        mkdir -p "$HOME/.zfunc"
        rustup completions zsh > "$HOME/.zfunc/_rustup"
    fi
    fpath+="$HOME/.zfunc"
fi

# opam (OCaml) configuration
[[ ! -r "$HOME/.opam/opam-init/init.zsh" ]] || source "$HOME/.opam/opam-init/init.zsh" > /dev/null 2> /dev/null

# ghcup (Haskell) configuration
[ -f "$HOME/.ghcup/env" ] && source "$HOME/.ghcup/env" # ghcup-env

# Nix configuration
if [ -e /home/bruno.parolini@olxbr.net/.nix-profile/etc/profile.d/nix.sh ]; then . /home/bruno.parolini@olxbr.net/.nix-profile/etc/profile.d/nix.sh; fi

autoload -Uz compinit && compinit

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

export LOCAL_USER_BIN="$HOME/.local/bin"
export PATH="$LOCAL_USER_BIN:$JAVA_HOME/bin:$GOROOT/bin:$GOBIN:$CARGO_BIN_HOME:$NVM_NODE_PATH/bin:$KAFKA_HOME/bin:$PATH"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# zoxide configuration
if [ ! $commands[zoxide] ]; then
    curl -sS https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | bash
fi
eval "$(zoxide init --cmd cd zsh)"

# fzf configuration -- MUST BE THE LAST ENTRY OR THE KEY-BINDINGS WON'T WORK
if [ $commands[fzf] ]; then
    if [ -f "$HOME/projetos/fzf/shell/completion.zsh" ]; then
        source "$HOME/projetos/fzf/shell/completion.zsh"
    fi
    if [ -f "$HOME/projetos/fzf/shell/key-bindings.zsh" ]; then
        source "$HOME/projetos/fzf/shell/key-bindings.zsh"
    fi
fi
